<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CareConnect.DTOs\CareConnect.DTOs.csproj" />
    <ProjectReference Include="..\CareConnect.AppServices\CareConnect.AppServices.csproj" />
    <ProjectReference Include="..\CareConnect.Infrastructure\CareConnect.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
