<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CareConnect.DTOs\CareConnect.DTOs.csproj" />
    <ProjectReference Include="..\CareConnect.Infrastructure\CareConnect.Infrastructure.csproj" />
    <ProjectReference Include="..\CareConnect.Commands\CareConnect.Commands.csproj" />
    <ProjectReference Include="..\CareConnect.Queries\CareConnect.Queries.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

</Project>
